/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: josephruotolo (https://sketchfab.com/josephruotolo)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/burger-baa6ab4da32444389a00c5a84b5a73e8
Title: Burger
*/


import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { a } from '@react-spring/three'
import BurgerScene from '../assets/3dburger/compressed.glb'


const BurgerModel = (props) => {
    const BurgerRef = useRef()

  const { nodes, materials } = useGLTF(BurgerScene)
  return (
    <a.group ref={BurgerRef} {...props}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['Cube001|Sphere|Dupli|_Material010_0'].geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube003_Material015_0_1.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube003_Material015_0.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube003_Material014_0.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube009_Material023_0.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube016_Material025_0.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube005_Material030_0.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere001_Material038_0.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube_Material001_0.geometry}
        material={materials.PaletteMaterial001}
        position={[28.084, -88.141, -58.322]}
        rotation={[-1.547, -0.176, -0.02]}
        scale={[100, 100, 50.471]}
      />
    </a.group>
  )
}

export default BurgerModel
